### ISSUE TITLE
Factory: Implement URL retriever

### ISSUE THREAD

**Issue by Azkali** [Azkali/Jet-Factory#1]
# Implementation idea

## Query URL

Query will be based on the following URL example :
`https://registry.hub.docker.com/v1/repositories/<container_name>/tags`
*Where container_name should represent the distribution name to query versions from*

## Parsing the version

- Ubuntu, Arch: Latest only
- Slackware: current only
- Fedora: Number sorting, high ( latest ) to low
- OpenSUSE:
    - Tumbleweed : only latest !
    - Leap :

**Comment by AD2076** [comment]
For slackware use -current.
Used to be stable enough
