### ISSUE TITLE
Factory: JSON Parsing

### ISSUE THREAD

**Issue by Azkali** [Azkali/Jet-Factory#2]
# Implementation Idea

The structure should be like following :
```go
type (
	// Base : Represent a distribution conatining a name, version, desktop environment and an optional list of packages
	Base struct {
		Name        string   `json:"distribution"`
		Configs     []string `json:"configs"`
		Packages    []string `json:"packages"`
		BuildArch   string   `json:"buildarch"`
		Mirrors     []string `json:"mirror_urls"`
		MirrorRegex string   `json:"regex"`

		// Variant : Represent a distribution variant
		Variant struct {
			Name     string   `json:"variants"`
			Configs  []string `json:"configs"`
			Packages []string `json:"packages"`
		} `json:"variants"`
	}
)
```

Then as for the parsing itself, it *should* unmarshall all the `JSON` in a `struct` at the very beginning of the file execution.
Then for each step, reuse another `Base` struct for the corresponding object to produce.

**Comment by AD2076** [comment]
Variant, android wisely, needs a name:
Base is lineage
variants are icosa, foster, foster_tab

**Comment by Azkali** [comment]
Yup that's the case :slightly_smiling_face:
